name: buildBulma
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: SpivEgin <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'


dev_dependencies:
#  build_runner: ^0.10.1
#  sass:
#    git: https://github.com/BulmaDart/dart-sass.git
  sass_builder: 2.1.1